{
 "title": "飞牛fnOS大盘（公开版）",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU使用率（User）",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fnos_cpu_cpu_busy_user" }
   ]
  },
  {
   "title": "CPU使用率（Sys）",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fnos_cpu_cpu_busy_system" }
   ]
  },
  {
   "title": "CPU使用率（IO）",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fnos_cpu_cpu_busy_iowait" }
   ]
  },
  {
   "title": "CPU温度",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fnos_cpu_cpu_temp", "legendFormat": "{{ device_name }}" }
   ]
  },
  {
   "title": "内存使用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fnos_memory_mem_used / fnos_memory_mem_total"
    }
   ]
  },
  {
   "title": "内存使用",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fnos_memory_mem_used" }
   ]
  },
  {
   "title": "Load-1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fnos_cpu_cpu_loadavg_avg1min" }
   ]
  },
  {
   "title": "Load-5",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fnos_cpu_cpu_loadavg_avg5min" }
   ]
  },
  {
   "title": "Load-15",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fnos_cpu_cpu_loadavg_avg15min" }
   ]
  },
  {
   "title": "卷使用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(fnos_store_array_fssize - fnos_store_array_frsize) / fnos_store_array_fssize",
     "legendFormat": "{{ array_name }}"
    }
   ]
  },
  {
   "title": "网络收发速度",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fnos_network_receive", "legendFormat": "{{ interface_name }}-收" },
    { "expr": "fnos_network_transmit", "legendFormat": "{{ interface_name }}-发" }
   ]
  },
  {
   "title": "GPU温度",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fnos_gpu_temp", "legendFormat": "{{ device_name }}" }
   ]
  },
  {
   "title": "磁盘温度",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fnos_disk_temp", "legendFormat": "{{ device_name }}" }
   ]
  },
  {
   "title": "GPU使用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fnos_gpu_busy" }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "fnos_cpu_cpu_busy_user", "legendFormat": "User%" },
    { "expr": "fnos_cpu_cpu_busy_system", "legendFormat": "System%" },
    { "expr": "fnos_cpu_cpu_busy_iowait", "legendFormat": "IO%" },
    { "expr": "fnos_cpu_cpu_busy_other", "legendFormat": "其它%" }
   ]
  },
  {
   "title": "CPU温度",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "fnos_cpu_cpu_temp", "legendFormat": "{{ cpu_name }}" }
   ]
  },
  {
   "title": "CPU负载",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "fnos_cpu_cpu_loadavg_avg5min", "legendFormat": "{{ cpu_name }} - load-5" },
    { "expr": "fnos_cpu_cpu_loadavg_avg1min", "legendFormat": "{{ cpu_name }} - load-1" },
    { "expr": "fnos_cpu_cpu_loadavg_avg15min", "legendFormat": "{{ cpu_name }} - load-15" }
   ]
  },
  { "title": "内存", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "fnos_memory_mem_used / fnos_memory_mem_total",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "交换区使用率",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "fnos_memory_swap_used / fnos_memory_swap_total",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "卷和磁盘",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  },
  {
   "title": "磁盘温度",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "fnos_disk_temp", "legendFormat": "{{ device_name }}" }
   ]
  },
  {
   "title": "卷空间使用",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(fnos_store_array_fssize - fnos_store_array_frsize) / fnos_store_array_fssize",
     "legendFormat": "{{ array_name }}"
    }
   ]
  },
  {
   "title": "磁盘读写速度",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "fnos_disk_read", "legendFormat": "{{ device_name }} - 读" },
    { "expr": "fnos_disk_write", "legendFormat": "{{ device_name }} - 写" }
   ]
  },
  { "title": "网络", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "网络速度",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "fnos_network_receive", "legendFormat": "收" },
    { "expr": "fnos_network_transmit", "legendFormat": "发" }
   ]
  }
 ]
}